name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    # Stage 1: Login to docker hub
    - name: Build Docker image
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

    # Stage 2: Build image
    - name: Build docker image
      run: docker build . --tag adv6-gui:latest

    # Stage 3: 
    - name: Push docker image to docker hub
      run: docker push ${{  secrets.DOCKER_USERNAME }}/adv6-gui:latest      
